{
  root: true,
  extends: [
    'openlayers',
    '.eslintrc-es6.yaml'
  ],
  settings: {
    'import/resolver': {
      'webpack': {}
    }
  },
  rules: {
    no-console: 0,
    comma-dangle: 0,
    no-extra-boolean-cast: 0,
    brace-style: 0,
    prefer-template: 0,
    no-multiple-empty-lines: 0,
    valid-jsdoc: 0,
  },
  globals: {
    webpack: false,
    Cesium: false
  }
}
