{
  root: true,
  extends: [
    'openlayers',
    '.eslintrc-es6.yaml'
  ],
  rules: {
    no-console: 0,
    comma-dangle: 0,
    no-extra-boolean-cast: 0,
    brace-style: 0,
    no-multiple-empty-lines: 0,
    valid-jsdoc: 0,
    indent: [2, 2, {
      VariableDeclarator: 2,
      SwitchCase: 1,
      MemberExpression: 2,
      FunctionDeclaration: {
        parameters: 2,
        body: 1
      },
      FunctionExpression: {
        parameters: 2,
        body: 1
      },
      CallExpression: {
        arguments: 2
      }
    }]
  },
  globals: {
    webpack: false,
    ol: false,
    goog: false,
    Cesium: false,
    olcs: false,
    proj4: false
  }
}
